### ISSUE TITLE
Fluid pipes don't connect to fluid storage tanks from other mods

### ISSUE THREAD

**Issue by ItchyFlea** [cyanobacterium/PowerAdvantageAPI#6]
Your fluid pipes do not connect to fluid storage tanks from other mods. I've tested both Fancy Fluid Storage and Buildcraft and your pipes do not connect to their fluid storage tanks.

Screenshot of FFS Tanks: http://imgur.com/2cAaXxS
Screenshot of BC Tanks: http://imgur.com/1ZvAQ2L

**Comment by DrPlantabyte** [comment]
You need to place a Drain next to the tank that you wish to withdraw fluids from and a Discharge Grate above a tank you wish to deposit into. The fluid pipes do not presently interact with normal fluid handlers because Power Advantage does not yet have an interface for normal fluid handlers.

I'll add direct fluid connections to the TODO list, but it will not be a simple change for the same reasons that supporting RF was not a simple feature to implement.

Here's a peek behind the curtain: the fluid pipes in Power Advantage have no internal data and thus the never "hold" fluids, therefore they are not fluid handlers. The fluid pipes are actually power conduits and the various types of fluids are turned into "fluid power" for instantaneous transmission from fluid source to fluid destination using the same code that handles steam and electricity.

**Comment by DrPlantabyte** [comment]
I had a eureka moment and came up with a clever and sneaky way to make the fluid pipes interact with fluid handlers from other mods. Now implemented in version 1.5.2
